name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci-investigation
  pull_request:
    paths-ignore:
      - doc/**
      - LICENSE
      - README.md

permissions:
  contents: read

jobs:
  test-on-vim:
    if: false
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        vim_version:
          # - v9.1.2110
          # - v9.1.2120
          # - v9.1.2125
          - v9.1.2130
          - v9.1.2131  # vim --version shows that it is v9.1.2132
          - v9.1.2132
          # - v9.1.2133
          # - v9.1.2134
          # - v9.1.2135

        download:
          - available

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20260116
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}

  investigation:
    if: false
    name: Vim ${{ matrix.vim_version }} ${{ matrix.configure_args }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        vim_version:
          - nightly
        configure_args:
          - --enable-gui=no --enable-fail-if-missing
          - --enable-gui=gtk3 --enable-fail-if-missing

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: apt install
        run: sudo apt-get install libxmu-dev libgtk-3-dev libxpm-dev
      - name: Setup Vim
        id: vim
        uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.vim_version }}
          configure-args: ${{ matrix.configure_args }}
      - name: Show Vim version
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: Setup themis.vim
        uses: actions/checkout@v6
        with:
          repository: thinca/vim-themis
          path: themis
      - name: Run test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./themis/bin/themis --reporter tap

  test:
    name: Vim ${{ matrix.vim_version }} with GUI=${{ matrix.enable_gui }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        vim_version:
          # - v9.1.0000
          # - v9.1.1000
          # - v9.1.2000
          # - v9.2.0000
          - nightly

        enable_gui:
          - no
          - gtk3

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install deps
        if: matrix.enable_gui == 'gtk3'
        run: sudo apt-get install libxmu-dev libgtk-3-dev libxpm-dev
      - name: Setup Vim
        id: vim
        uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.vim_version }}
          configure-args: |
            --enable-gui=${{ matrix.enable_gui }} --enable-fail-if-missing
      - name: Show Vim version
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: Prepare test code
        run: |
          cat - <<EOF > ./test.vim
          let g:input = []
          function TakeInput() abort
            call add(g:input, input(''))
          endfunction

          let g:log = []
          autocmd CmdlineEnter @ call add(g:log, 'CmdlineEnter:@')
          autocmd CmdlineEnter * call add(g:log, $'CmdlineEnter(any):{expand('<afile>')}')

          nnoremap <expr> <Plug>(take-input) TakeInput()
          call setreg('q', "\<Plug>(take-input)")
          call feedkeys("@qxyzabc\<CR>", 'ni')
          call feedkeys('', 'x')

          call add(g:log, '------')
          call feedkeys("\<Plug>(take-input)hij987\<CR>", 'ni')
          call feedkeys('', 'x')

          call add(g:log, '------')
          call feedkeys("asdf\<CR>", 'ni')
          call add(g:input, input(''))

          %delete _
          call setline(1, '===autocmd-log===')
          call append('$', g:log)
          call append('$', '===input===')
          call append('$', g:input)
          %print

          if len(g:log) == 5
            quitall!
          else
            cquit! 13
          endif
          EOF
      - name: Run test
        run: |
          ${{ steps.vim.outputs.executable }} -u NONE -i NONE -n -N -e -s --cmd 'source ./test.vim'
