name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci-investigation
  pull_request:
    paths-ignore:
      - doc/**
      - LICENSE
      - README.md

permissions:
  contents: read

jobs:
  test-on-vim:
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        vim_version:
          - v9.1.0000
          - v9.1.1000
          - head

        download:
          - available

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20260116
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}
